config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    before_validation { email.downcase! }
    validates :name, presence: true, length: {maximum: 30}
    validates :email, presence: true, length: {maximum: 255},
                format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                uniqueness: true

    has_secure_password
    validates :password, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    include SessionsHelper
    before_action :login_required

    private
    def login_required
        redirect_to new_session_path unless current_user
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'Failed to login'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'Logout succesfully'
    redirect_to new_session_path
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            redirect_to user_path(@user.id)
        else
            render :new
        end
    end

    def show
        @user = User.find(params[:id])
    end
    


    private

    def user_params
        params.require(:user).permit(:name, :email, :password,
                                     :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end

    def logged_in?
        current_user.present?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AuthCrs</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
    .danger{
      color: red;
    }
    </style>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>

    <header>
      
      <% if logged_in? %>
        <%= link_to "Profile", user_path(current_user.id)%> 
        <%= link_to "Logout", session_path(current_user.id), method: :delete%> 
      <% else%> 
        <%= link_to "Sign up", new_user_path%> 
        <%= link_to "Login", new_session_path%> 
      <% end%> 

      
    </header>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>S'inscrire</h1>


<% if @user.errors.any? %>
<div id = "error_explanation"> 
    <h2> <%= pluralize(@user.errors.count, "error")%> a interdit l'enregistrement de ce <%= @user.name%>: </h2> 
    <ul style="color: red"> 
        <% @user.errors.full_messages.each do | message |%> 
        <li> <%= message%> </li> 
        <% end%> 
    </ul> 
 </div> 
 <% end%> 


<%= form_with(model: @user, local: true) do |f| %>
    <%= f.label :name, "Name" %>
    <%= f.text_field :name %>
    <br>
    <%= f.label :email, "Email" %>
    <%= f.email_field :email %>
    <br>
    <%= f.label :password, "Password" %>
    <%= f.password_field :password %>
    <br>
    <%= f.label :password_confirmation, "Confirm Password" %>
    <%= f.password_field :password_confirmation %>
    <br>
    <%= f.submit "Créer mon compte" %>
<% end %>

app/views/users/show.html.erb
<h1>Mes informations</h1>

<div>
    <p> Name : <%= @user.name%> </p>
    <p> Email : <%= @user.email%> </p>
</div>